version: '3.8'

services:
  postgis:
    image: postgis/postgis:14-3.2
    expose:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file: .env

  web:
    build: .
    ports:
      - "8111:8111"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8111"
    volumes:
      - .:/usr/src/app
      - ./media:/usr/src/app/media
      - ./static:/usr/src/app/static
    env_file: .env
    depends_on:
      - postgis

#  nginx:
#    build: ./nginx
#    ports:
#      - '80:80'
#    volumes:
#      - ./media:/media
#      - ./static:/static
#      - ./dhparam.pem:/etc/ssl/private/dhparam.pem
#      - /etc/letsencrypt:/etc/letsencrypt
#      - /var/lib/letsencrypt:/var/www/certbot


networks:
  default:
    external:
      name: external-example